---
title: "Lecture 12 Growth curves"
author: "Beth Babcock"
date: "`r Sys.Date()`"
output: html_document
---

```{r, message=FALSE}
library(R2jags)
library(tidyverse)
library(ggmcmc)
library(rstan)
library(loo)
library(gridExtra)
library(shinystan)
library(here)
theme_set(theme_bw())
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```


## Yellowtail example

```{r}
yellowtail<-read.csv(here("data","yellowtail.csv"))
summary(yellowtail)
ggplot(yellowtail, aes(x=Age,y=ObsL))+
 geom_point()+xlab("Age")+ylab("Length")
```

Model in JAGS with lognormal error

```{r}
write("model {
	for (i in 1:N){ 
		PredL[i] <- Linf * (1 - exp(- K* (Age[i] -Age0))) 	# model prediction  
		logPredL[i] <- log(PredL[i])  	# log-transformation of pred.value
		ObsL[i] ~ dlnorm(logPredL[i], tau)  	# lognormal likelihood
		logObsL[i] <-log(ObsL[i]) 	     # log transfomration of observed value
		 resid[i] <- logObsL[i]-logPredL[i]  # residuals
	 	repL[i] ~ dlnorm(logPredL[i], tau) # replicated data set
	 	logRep[i] <-log(repL[i]) # replicated data set
   sresid2[i]<-(logObsL[i]-logPredL[i])*(logObsL[i]-logPredL[i])*tau   # stand. residuals squared
   rep.sresid2[i]<-(logRep[i]-logPredL[i])*(logRep[i]-logPredL[i])*tau  # replicated sresid squared
}
 #priors specification
  K ~ dunif(0,4)
  Age0~ dunif(-15,0)
  Linf ~ dunif(10,3000) 	
  tau~dgamma(0.001,0.001)
  #Derived parameters
    chi.square.obs<-sum(sresid2[])
    chi.square.rep<-sum(rep.sresid2[])
    p.value<-step(chi.square.obs-chi.square.rep)
}
",file=here("JAGS_mods","VonBertLnorm.txt"))

init1=list(tau=1,Linf=1200,K=0.6,Age0=-0.1)
init2=list(tau=0.5,Linf=1000,K=0.4,Age0=-0.3)

yellowtailList=list(N=dim(yellowtail)[1],Age=yellowtail$Age,ObsL=yellowtail$ObsL)

res1jags=jags(yellowtailList,list(init1,init2),
  model.file=here("JAGS_mods","VonBertLnorm.txt"),
                parameters.to.save=c("K","Linf","tau","Age0","p.value",
                  "resid","PredL","repL","chi.square.obs","chi.square.rep"),
                n.chains=2,n.iter=110000,n.burnin=10000,n.thin=4)
res1<-res1jags$BUGSoutput
range(res1$summary[,"n.eff"])
range(res1$summary[,"Rhat"])
ggs1<-ggs(as.mcmc(res1jags)) %>% filter(Parameter %in% c("K","Linf","Age0"))
ggs_autocorrelation(ggs1)
ggs_pairs(ggs1,lower=list(continuous="density"))
res1$DIC
res1$pD
```


Schnute parameterization lognormal

```{r}
write("model 
  {
		for (i in 1:N){ 
			PredL[i] <- L1 +(L2-L1)* (1 - exp(- K* (Age[i] -Age1)))/(1 - exp(- K* (Age2 -Age1))) 	# model prediction  
			logPredL[i] <- log(PredL[i])  	# log-transformation of pred.value
			ObsL[i] ~ dlnorm(logPredL[i], tau)  	# lognormal likelihood
			logObsL[i] <-log(ObsL[i]) 	     # log transfomration of observed value
			 resid[i] <- logObsL[i]-logPredL[i]  # residuals
		 	Rep[i] ~ dlnorm(logPredL[i], tau) # replicated data set
		 	logRep[i] <-log(Rep[i]) # replicated data set
		  sresid2[i]<-(logObsL[i]-logPredL[i])*(logObsL[i]-logPredL[i])*tau   
      rep.sresid2[i]<-(logRep[i]-logPredL[i])*(logRep[i]-logPredL[i])*tau 
		}
  #priors specification
     K ~ dunif(0,2)
	   Age1<-1
	   Age2<-8
     L1~dunif(10,3000) 	
     L2~dunif(10,3000) 	
     tau~dgamma(0.001,0.001)
  #Derived parameters
    Linf<- (L2-L1*exp(-K*(Age2-Age1)))/(1-exp(-K*(Age2-Age1)))
    chi.square.obs<-sum(sresid2[])
    chi.square.rep<-sum(rep.sresid2[])
    p.value<-step(chi.square.obs-chi.square.rep)
}
",file=here("JAGS_mods","VonBertLnormSchnute.txt"))

init1=list(tau=1,L1=500,L2=1200,K=0.6)
init2=list(tau=0.5,L1=400,L2=1000,K=0.4)

res2jags<-jags(yellowtailList,list(init1,init2),model.file=here("JAGS_mods","VonBertLnormSchnute.txt"),
              parameters.to.save=c("K","Linf","L1","L2","tau","p.value",
                "resid","PredL","logPredL", "chi.square.obs","chi.square.rep","Prob"),
              n.chains=2,n.iter=110000,n.burnin=10000,n.thin=4)
res2<-res2jags$BUGSoutput
range(res2$summary[,"n.eff"])
range(res2$summary[,"Rhat"])

ggs2<-ggs(as.mcmc(res2jags)) %>% filter(Parameter %in% c("K","L1","L2"))
ggs_autocorrelation(ggs2)
ggs_pairs(ggs2,lower=list(continuous="density"))
```

Plot fit

```{r}
df1<-data.frame(res2$summary[paste0("PredL[",1:88,"]"),
  c("mean","2.5%","50%","97.5%")])
names(df1)<-c("mean","lci","median","uci")
df1<-cbind(df1,yellowtail)
ggplot(df1,aes(x=Age,y=ObsL,ymin=lci,ymax=uci))+geom_point()+
  geom_ribbon(alpha=0.3)+theme_bw()+geom_line(aes(x=Age,y=mean))+ylab("Length")
res2$DIC
res2$pD
round(res2$summary[c("L1","L2","Linf","K","p.value"),],2)
#plot resids
n<-dim(yellowtail)[1]
sumtab<-res2$summary
residrows<-paste0("resid[",1:n,"]")
meanrows<-paste0("logPredL[",1:n,"]")
dfcheck<-data.frame(Predicted=sumtab[meanrows,"mean"],
  Residual=sumtab[residrows,"mean"])
ggplot(dfcheck)+
  geom_point(aes(x=Predicted,y=Residual))+
  geom_abline(intercept=0,slope=0)+ggtitle("Residuals")
ggplot(dfcheck,aes(sample=Residual))+
  geom_qq()+geom_qq_line()+ggtitle("QQNormal of Residuals")
```

Schnute with normal residuals

```{r}
write("model {
  for (i in 1:N){ 
   PredL[i] <- L1 +(L2-L1)* (1 - exp(- K* (Age[i] -Age1)))/(1 - exp(- K*(Age2 -Age1))) 	#  model prediction  
   ObsL[i] ~ dnorm(PredL[i], tau)  	#Normal likelihood
   resid[i] <- ObsL[i] - PredL[i]  # residuals
   Rep[i] ~ dnorm(PredL[i], tau) #  replicated data set
   Prob[i] <- step(Rep[i] - ObsL[i])  # Probability replicated data>real data
   sresid2[i]<-(ObsL[i]-PredL[i])*(ObsL[i]-PredL[i])*tau   # standardized residuals squared
   rep.sresid2[i]<-(Rep[i]-PredL[i])*(Rep[i]-PredL[i])*tau  # replicated sresid squared
}
 #priors specification
 K ~ dunif(0,2)
 Age1<-2
 Age2<-7
 L1~dunif(10,3000) 	
 L2~dunif(10,3000) 	
 tau~dgamma(0.001,0.001)
 #Derived parameters
 Linf<- (L2-L1*exp(-K*(Age2-Age1)))/(1-exp(-K*(Age2-Age1)))
 mean.prob<-mean(Prob[])
 chi.square.obs<-sum(sresid2[])
 chi.square.rep<-sum(rep.sresid2[])
 p.value<-step(chi.square.obs-chi.square.rep)
}",here("JAGS_mods","VonBertNormalSchnute.txt"))

init1<-list(tau=1,L1=500,L2=1200,K=0.6)
init2<-list(tau=0.5,L1=400,L2=1000,K=0.4)
res3jags<-jags(yellowtailList,list(init1,init2),model.file=here("JAGS_mods","VonBertNormalSchnute.txt"),
              parameters.to.save=c("K","Linf","L1","L2","tau","p.value","resid","PredL","Rep",
                                   "chi.square.obs","chi.square.rep","Prob"),
              n.chains=2,n.iter=110000,n.burnin=10000,n.thin=4)
res3<-res3jags$BUGSoutput
range(res3$summary[,"n.eff"])
range(res3$summary[,"Rhat"])
#plot resids
n<-dim(yellowtail)[1]
sumtab<-res3$summary
residrows<-paste0("resid[",1:n,"]")
meanrows<-paste0("PredL[",1:n,"]")
dfcheck<-data.frame(Predicted=sumtab[meanrows,"mean"],
  Residual=sumtab[residrows,"mean"])
ggplot(dfcheck)+geom_point(aes(x=Predicted,y=Residual))+geom_abline(intercept=0,slope=0)+ggtitle("Residuals")
ggplot(dfcheck,aes(sample=Residual))+geom_qq()+geom_qq_line()+ggtitle("QQNormal of Residuals")

round(res2$summary[c("L1","L2","K","Linf","tau","p.value"),c("mean","sd","2.5%","50%","97.5%")],2)
round(res3$summary[c("L1","L2","K","Linf","tau","p.value"),c("mean","sd","2.5%","50%","97.5%")],5)

res2$DIC
res3$DIC
```

Lognormal regular parameterization in STAN

```{r}
write("data {
  int<lower=0> N;
  vector[N] ObsL;
  vector[N] Age;
}
parameters {
  real<lower=10, upper=2000> Linf;
  real<lower=0, upper=4> K;
  real<lower=-15,upper=0> Age0;
  real<lower=0> sigma;
}
transformed parameters {
  vector[N] PredL;
  vector[N] logPredL;
  for(i in 1:N) {
		PredL[i] = Linf * (1 - exp(- K* (Age[i] -Age0))); 
		logPredL[i] = log(PredL[i]);  
  }
}
model {
  K ~ uniform(0,4);
  Age0~ uniform(-15,0);
  Linf ~ uniform(10,3000); 	
  sigma ~ uniform(0.01,1);
  for(i in 1:N) {
    ObsL[i] ~ lognormal(logPredL[i], sigma);
  }
}
generated quantities {
  vector[N] LL;
  vector[N] residual;
  vector[N] repL;
  for(i in 1:N) {
  		LL[i] = lognormal_lpdf(ObsL[i]|logPredL[i],sigma);
  		residual[i] = log(ObsL[i])-logPredL[i];
      repL[i] = lognormal_rng(logPredL[i],sigma);
  }
}
",
  file=here("STAN_docs","stanGrowthLN.stan"))
yellowtailStan1<-stan(file=here("STAN_docs","stanGrowthLN.stan"),
  data=yellowtailList)
obsL<-yellowtail$ObsL #This makes the y variable discoverable 
#launch_shinystan(yellowtailStan1)

print(yellowtailStan1,par=c("K","Linf","sigma","Age0"))
gg1<-ggs(yellowtailStan1) %>% filter(Parameter %in% c("K","Linf","Age0"))
ggs_pairs(gg1)
```

Lognormal Schnute parameterization in STAN

```{r}
write("
data {
  int<lower=0> N;
  vector[N] ObsL;
  vector[N] Age;
  real  Age1;
  real  Age2;
}
parameters {
  real<lower=10, upper=2000> L1;
  real<lower=10, upper=3000> L2;
  real<lower=0, upper=4> K;
  real<lower=0> sigma;
}
transformed parameters {
  vector[N] PredL;
  vector[N] logPredL;
  for(i in 1:N) {			
    PredL[i] = L1 +(L2-L1)* (1 - exp(- K* (Age[i] -Age1)))/(1 - exp(- K* (Age2 -Age1))); 
		logPredL[i] = log(PredL[i]);  
  }
}
model {
  K ~ uniform(0,4);
  L1 ~ uniform(10,3000); 	
  L2 ~ uniform(10,2000); 	
  sigma ~ uniform(0.01,1);
  for(i in 1:N) {
    ObsL[i] ~ lognormal(logPredL[i], sigma);
  }
}
generated quantities {
  vector[N] LL;
  vector[N] residual;
  vector[N] repL;
  real      Linf;
  Linf= (L2-L1*exp(-K*(Age2-Age1)))/(1-exp(-K*(Age2-Age1)));
  for(i in 1:N) {
  		LL[i] = lognormal_lpdf(ObsL[i]|logPredL[i],sigma);
  		residual[i] = log(ObsL[i])-logPredL[i];
      repL[i] = lognormal_rng(logPredL[i],sigma);
  }
}
",
  file=here("STAN_docs","stanGrowthLNSchnute.stan"))

yellowtailList2=list(N=dim(yellowtail)[1],Age=yellowtail$Age,ObsL=yellowtail$ObsL,
  Age1=1,Age2=8)

yellowtailStan2<-stan(file=here("STAN_docs","stanGrowthLNSchnute.stan"),
  data=yellowtailList2)
print(yellowtailStan2,par=c("L1","L2","K","sigma","Linf"))
#launch_shinystan(yellowtailStan2)
gg2<-ggs(yellowtailStan2) %>% filter(Parameter %in% c("K","L1","L2"))
ggs_pairs(gg2)

```


## Dugong example with errors in variables from Lunn

```{r}
dugong<-list(x = c(1.0,  1.5,  1.5,  1.5, 2.5,   4.0,  5.0,  5.0,  7.0,
  8.0,  8.5,  9.0,  9.5, 9.5,  10.0, 12.0, 12.0, 13.0,
  13.0, 14.5, 15.5, 15.5, 16.5, 17.0, 22.5, 29.0, 31.5),
  y = c(1.80, 1.85, 1.87, 1.77, 2.02, 2.27, 2.15, 2.26, 2.47,
    2.19, 2.26, 2.40, 2.39, 2.41, 2.50, 2.32, 2.32, 2.43,
    2.47, 2.56, 2.65, 2.47, 2.64, 2.56, 2.70, 2.72, 2.57),
  n = 27)
dugong2<-data.frame(Age=dugong$x,Length=dugong$y)
ggplot(dugong2,aes(x=Age,y=Length))+geom_point()+theme_bw()

write("model {
  for(j in 1:n) {
    y[j]       ~ dnorm(mu[j], tau)
    mu[j]     <- alpha - beta*pow(gamma, z[j])
    x[j]       ~ dnorm(z[j], 1)
    z[j]       ~ dunif(0, 100)
  }
  alpha        ~ dunif(0, 100)
  beta         ~ dunif(0, 100)
  gamma        ~ dunif(0, 1)
  tau         <- 1/sigma2
  log(sigma2) <- 2*log.sigma
  log.sigma    ~ dunif(-10, 10)
  for (j in 1:n) {resx[j] <- x[j] - z[j]}
}",file=here("JAGS_mods","dugong.txt"))
init1<-list(alpha = 3, beta = 2, gamma = 0.9, log.sigma = -5)
init2<-list(alpha = 2, beta = 1, gamma = 0.7, log.sigma = -4)
resdug<-jags(dugong,list(init1,init2),model.file=here("JAGS_mods","dugong.txt"),
  parameters.to.save=c("alpha","beta","gamma","z","resx","mu","sigma2"),
  n.chains=2,n.iter=110000,n.burnin=10000,n.thin=4)
range(resdug$BUGSoutput$summary[,"n.eff"])
range(resdug$BUGSoutput$summary[,"Rhat"])

agerow<-paste("z[",1:dugong$n,"]",sep="")
meanrow<-paste("mu[",1:dugong$n,"]",sep="")
df1<-data.frame(cbind(resdug$BUGSoutput$summary[agerow,c("mean","2.5%","97.5%")],
 resdug$BUGSoutput$summary[meanrow,c("mean","2.5%","97.5%")]))
names(df1)<-c("PredAge","agemin","agemax","PredL","Lmin","Lmax")
df1<-cbind(df1,dugong2)
head(df1)
ggplot(df1)+geom_point(aes(x=Age,y=Length))+
  geom_point(aes(x=PredAge,y=Length),col="red")+
  geom_ribbon(aes(x=PredAge,ymin=Lmin,ymax=Lmax),alpha=0.3,fill="red")+
  geom_line(aes(x=PredAge,y=PredL),col="red")+theme_bw()

#Dugong without error in x variable
write("model {
  for(j in 1:n) {
    y[j]       ~ dnorm(mu[j], tau)
    mu[j]     <- alpha - beta*pow(gamma, x[j])
   }
  alpha        ~ dunif(0, 100)
  beta         ~ dunif(0, 100)
  gamma        ~ dunif(0, 1)
  tau         <- 1/sigma2
  log(sigma2) <- 2*log.sigma
  log.sigma    ~ dunif(-10, 10)
}",file=here("JAGS_mods","dugongNoError.txt"))
resdug2<-jags(dugong,list(init1,init2),model.file=here("JAGS_mods","dugongNoError.txt"),
  parameters.to.save=c("alpha","beta","gamma","mu","sigma2"),
  n.chains=2,n.iter=110000,n.burnin=10000,n.thin=4)

df2<-data.frame(resdug2$BUGSoutput$summary[meanrow,c("mean","2.5%","97.5%")])
names(df2)<-c("PredL2","Lmin2","Lmax2")
df1<-cbind(df1,df2)
ggplot(df1)+geom_point(aes(x=Age,y=Length))+
  geom_point(aes(x=PredAge,y=Length),col="red")+
  geom_ribbon(aes(x=PredAge,ymin=Lmin,ymax=Lmax),alpha=0.3,fill="red")+
  geom_line(aes(x=PredAge,y=PredL),col="red")+
  geom_ribbon(aes(x=Age,ymin=Lmin2,ymax=Lmax2),alpha=0.3,fill="blue")+
  geom_line(aes(x=Age,y=PredL2),col="blue")+theme_bw()
```


##  For abalone from Zhang et al. 2009

```{r}
abalone<-read.csv(here("data","abalone.csv"))
summary(abalone)
altbacoreList<-as.list(abalone[,2:7])
for(i in 1:6)
   altbacoreList[[i]]<-altbacoreList[[i]][!is.na(altbacoreList[[i]])]
init1=list(Ltau=1,Ktau=1,tau=1,A=c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1))
init2=list(Ltau=2,Ktau=2,tau=2,A=c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1))

write("model   {
 for (i in 1:24)  {  # all recap individuals
    # Each individual draws Linf, K, and age
   Linf[i]~dnorm(Lmean,Ltau) # random Linf
   K[i]~dnorm(Kmean,Ktau) # random K
   A[i]~dgamma(s,r)T(0.5, 30) #random age
   # Predict size at capture and first recapture
   Lpred0[i]<-Linf[i]*(1-exp(-K[i]*A[i]))  
    Lpred1[i]<-Linf[i]*(1-exp(-K[i]*(A[i]+deltime[i])))
   #Likelihood of measured sizes  
    Ltag[i]~dnorm(Lpred0[i],tau)     
    Lrec[i]~dnorm(Lpred1[i],tau)
  } 
 for(i in 1:7)  {  # all with 2 recaps   
   Lpred2[i]<-Linf[indiv2[i]]*(1-exp(-K[indiv2[i]]*(A[indiv2[i]]+deltime[i]+deltime2[i])))
   Lrec2[i]~dnorm(Lpred2[i],tau)
}
 # priors specification (all random effects)
  Ltau~dgamma(0.001,0.0001)
  Lvar<-1/Ltau
  Ktau~dgamma(0.001,0.0001)
  Kvar<-1/Ktau
  Lmean~dnorm(100,1.0E-6)T(0,)
  Kmean~dbeta(1,1)
  tau~dgamma(0.0001,0.0001)
  s~dunif(0,100)   #for random Age at 1st capture
  r~dunif(0,100)
}
",file=here("JAGS_mods","growthZhangOriginalJags.txt"))
zhang1j<-jags(altbacoreList,list(init1,init2),model.file=here("JAGS_mods","growthZhangOriginalJags.txt"),
              parameters.to.save=c("Linf","K","A","s","r","Lmean","Ltau","Kmean","Ktau"),
              n.chains=2,n.iter=110000,n.burnin=10000,n.thin=4)
range(zhang1j$BUGSoutput$summary[,"n.eff"])
range(zhang1j$BUGSoutput$summary[,"Rhat"])
zhang1j$BUGSoutput$DIC
zhang1j$BUGSoutput$pD
round(zhang1j$BUGSoutput$summary[c("Lmean","Kmean"),c("mean","sd","2.5%","50%","97.5%")],5)
Krow<-paste("K[",1:24,"]",sep="")
Lrow<-paste("Linf[",1:24,"]",sep="")
par(mfrow=c(2,2))
hist(zhang1j$BUGSoutput$sims.matrix[,"Kmean"],main="Mean K",breaks=seq(0,3.1,0.05),xlab="K",prob=T,xlim=c(0,1))
hist(zhang1j$BUGSoutput$sims.matrix[,"Lmean"],main="Mean Linf",breaks=seq(50,150,5),xlab="Linf",prob=T,xlim=c(50,150))
hist(c(zhang1j$BUGSoutput$sims.matrix[,Krow]),main="Individual K",breaks=seq(0,10,0.05),xlab="K",prob=T,xlim=c(0,1))
hist(c(zhang1j$BUGSoutput$sims.matrix[,Lrow]),main="Individual Linf",breaks=seq(50,205,5),xlab="Linf",prob=T,xlim=c(50,150))
``` 


